---
build_idm: false
build_sat: false
automation_hub: false

pattern_name: '{{ ec2_name_prefix }}'

controller_hostname: 'aap.{{ pattern_name }}.{{ pattern_dns_zone }}'
gateway_hostname: "{{ controller_hostname }}"
controller_port: 8443
gateway_port: 443
hub_port: 8444
eda_port: 8445

controller_state: present

agof_configure_aap_debug: false
controller_request_timeout: 90
controller_configuration_async_dir: /tmp/.ansible_async
